version: '3.5'

services:
  db-postgresql:
    image: postgres
    hostname: db-postgresql
    environment:
      - POSTGRES_USER=rinhabackend
      - POSTGRES_PASSWORD=rinhabackend
      - POSTGRES_DB=rinhadb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c max_connections=250 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '250MB'
