version: '3.5'

services:
  api1: &api1 # API - Instância 01
    image: wesleyegberto/rinha-backend-2024-q1-jvm
    # image: wesleyegberto/rinha-backend-2024-q1-native
    hostname: api1
    networks:
      - rinha-backend
    depends_on:
      - db
    environment:
      - PORT=8080
      - DATABASE_HOST=db
      - DATABASE_NAME=rinhadb
      - DATABASE_USERNAME=rinhabackend
      - DATABASE_PASSWORD=rinhabackend
      - JAVA_TOOL_OPTIONS=-XX:+UseSerialGC -Xss136K -Xmx512M -XX:ReservedCodeCacheSize=128M
      - BPL_JVM_THREAD_COUNT=100
      - GC_MAX_METASPACE_SIZE=100
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '1.25'
          memory: '1024MB'

  api2: # API - Instância 02
    <<: *api1
    hostname: api2
    environment:
      - PORT=8081
      - DATABASE_HOST=db
      - DATABASE_NAME=rinhadb
      - DATABASE_USERNAME=rinhabackend
      - DATABASE_PASSWORD=rinhabackend
      - JAVA_TOOL_OPTIONS=-XX:+UseSerialGC -Xss136K -Xmx512M -XX:ReservedCodeCacheSize=128M
      - BPL_JVM_THREAD_COUNT=100
    expose:
      - "8081"

  nginx: # Load Balancer
    image: nginx
    networks:
      - rinha-backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    expose:
      - "9999"
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '50MB'

  db: # Banco de dados
    image: postgres
    hostname: db
    networks:
      - rinha-backend
    environment:
      - POSTGRES_USER=rinhabackend
      - POSTGRES_PASSWORD=rinhabackend
      - POSTGRES_DB=rinhadb
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c max_connections=1000 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '250MB'
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  rinha-backend:
    driver: bridge
