version: '3.5'

services:
  api1: # API - Instância 01
    image: wesleyegberto/rinhabackend2024q1-java-jvm
    hostname: api1
    # networks:
    #   - rinha-backend
    network_mode: host
    depends_on:
      - db
    environment:
      - PORT=8080
      - DATABASE_HOST=127.0.0.1
      - DATABASE_NAME=rinhadb
      - DATABASE_USERNAME=rinhabackend
      - DATABASE_PASSWORD=rinhabackend
    expose:
      - "8080"
    ports:
      - "127.0.0.1:8080:8080"
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '125MB'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api2: # API - Instância 02
    image: wesleyegberto/rinhabackend2024q1-java-jvm
    hostname: api2
    # networks:
      # - rinha-backend
    network_mode: host
    depends_on:
      - db
    environment:
      - PORT=8081
      - DATABASE_HOST=127.0.0.1
      - DATABASE_NAME=rinhadb
      - DATABASE_USERNAME=rinhabackend
      - DATABASE_PASSWORD=rinhabackend
    expose:
      - "8081"
    ports:
      - "127.0.0.1:8081:8081"
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '125MB'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx: # Load Balancer
    image: nginx
    # networks:
      # - rinha-backend
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    expose:
      - "9999"
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '50MB'
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  db: # Banco de dados
    image: postgres
    # networks:
      # - rinha-backend
    network_mode: host
    environment:
      - POSTGRES_USER=rinhabackend
      - POSTGRES_PASSWORD=rinhabackend
      - POSTGRES_DB=rinhadb
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '250MB'
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  rinha-backend:
    # removido para utilizar network_mode host no lugar de bridge (tradução de tráfego na rede virtual dropando conexões)
    # driver: bridge
    external: true
    name: host
