version: '3.5'

services:
  api1: # API - Instância 01
    image: wesleyegberto/rinhabackend2024q1-java-jvm
    hostname: api1
    networks:
      - rinha-backend
    depends_on:
      - db
    environment:
      - PORT=8080
      - DATABASE_HOST=db
      - DATABASE_NAME=rinhadb
      - DATABASE_USERNAME=rinhabackend
      - DATABASE_PASSWORD=rinhabackend
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '125MB'

  api2: # API - Instância 02
    image: wesleyegberto/rinhabackend2024q1-java
    hostname: api2
    networks:
      - rinha-backend
    depends_on:
      - db
    environment:
      - PORT=8081
      - DATABASE_HOST=db
      - DATABASE_NAME=rinhadb
      - DATABASE_USERNAME=rinhabackend
      - DATABASE_PASSWORD=rinhabackend
    expose:
      - "8081"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '125MB'

  nginx: # Load Balancer
    image: nginx
    networks:
      - rinha-backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    expose:
      - "9999"
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '50MB'

  db: # Banco de dados
    image: postgres
    networks:
      - rinha-backend
    environment:
      - POSTGRES_USER=rinhabackend
      - POSTGRES_PASSWORD=rinhabackend
      - POSTGRES_DB=rinhadb
    expose:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '250MB'
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  rinha-backend:
    driver: bridge
